import os
import json
from pathlib import Path
from dotenv import load_dotenv

ROLES_TEMPLATE = {
    "V1": {
        "role": "Organization Manager",
        "description": "Manages GitHub organization, repositories, and high-level strategy.",
        "key_type": "GITHUB_PAT"
    },
    "V2": {
        "role": "Repository Admin",
        "description": "Handles repository settings, CI/CD, and access control.",
        "key_type": "GITHUB_PAT"
    },
    "V3": {
        "role": "Personal Assistant / Developer",
        "description": "Assists with daily coding tasks, automation, and general queries.",
        "key_type": "GITHUB_PAT",
        "email": "genxdbxfx3@gmail.com"
    },
    "V4": {
        "role": "Trading Strategy Analyst",
        "description": "Focuses on analyzing trading signals and market data.",
        "key_type": "AGENT_TOKEN"
    },
    "V5": {
        "role": "Risk Management Agent",
        "description": "Monitors open positions, margin levels, and calculates risk.",
        "key_type": "AGENT_TOKEN"
    },
    "V6": {
        "role": "Execution Engine",
        "description": "Handles placing and modifying orders on trading platforms.",
        "key_type": "AGENT_TOKEN"
    },
    "V7": {
        "role": "Data Sync Agent",
        "description": "Synchronizes data between APIs, databases, and spreadsheets.",
        "key_type": "AGENT_TOKEN"
    },
    "V8": {
        "role": "System Monitor",
        "description": "Tracks system health, API limits, and performance metrics.",
        "key_type": "AGENT_TOKEN"
    },
    "V9": {
        "role": "Communication Hub",
        "description": "Manages notifications to Telegram, Discord, and WhatsApp.",
        "key_type": "AGENT_TOKEN"
    },
    "V10": {
        "role": "ML/AI Predictor",
        "description": "Runs machine learning models for market prediction.",
        "key_type": "AGENT_TOKEN"
    },
    "V11": {
        "role": "Device Manager NUNA",
        "description": "Manages local environment and hardware specific configurations on NUNA (Vivobook Go E1504GAB).",
        "key_type": "AGENT_TOKEN"
    }
}

def load_keys():
    load_dotenv()
    for v_id in ROLES_TEMPLATE:
        key = os.getenv(f"AGENT_{v_id}_KEY", f"<{v_id}_KEY_PLACEHOLDER>")
        ROLES_TEMPLATE[v_id]["key"] = key
    return ROLES_TEMPLATE

def generate_env_template():
    env_content = "# AI Roleplay Agents Configuration Template\n"
    env_content += "# Generated by roleplay_manager.py\n"
    env_content += "# Copy this file to .env.roles and replace placeholders with actual keys.\n\n"

    for v_id, config in ROLES_TEMPLATE.items():
        env_content += f"# {v_id} - {config['role']}\n"
        env_content += f"# {config['description']}\n"
        env_content += f"AGENT_{v_id}_KEY=<{v_id}_{config['key_type']}_PLACEHOLDER>\n"
        env_content += f"AGENT_{v_id}_ROLE=\"{config['role']}\"\n\n"

    env_path = Path(".env.roles.template")
    with open(env_path, "w") as f:
        f.write(env_content)
    print(f"✅ Generated {env_path}")

def generate_json_config():
    config_path = Path("config/agent_roles.json")
    config_path.parent.mkdir(parents=True, exist_ok=True)

    # Store config without hardcoding keys
    safe_config = {v_id: {k: v for k, v in config.items() if k != 'key'} for v_id, config in ROLES_TEMPLATE.items()}
    with open(config_path, "w") as f:
        json.dump(safe_config, f, indent=4)
    print(f"✅ Generated {config_path}")

if __name__ == "__main__":
    print("🚀 Starting Agent Roleplay Manager Setup...")
    load_keys()
    generate_env_template()
    generate_json_config()
    print("✨ Setup complete! Template files generated. Be sure to keep actual keys in your local .env file.")
