"""
WhatsApp Bot Service for GenX Trading Platform
Sends trading signals and notifications to WhatsApp groups
"""

import os
import logging
from typing import Dict, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class WhatsAppBot:
    """WhatsApp bot for sending trading signals and notifications to groups"""

    def __init__(self):
        """Initialize WhatsApp bot with configuration from environment"""
        self.group_url = os.getenv("WHATSAPP_GROUP_URL", "")
        self.enabled = bool(self.group_url)

        if self.enabled:
            logger.info(f"WhatsApp bot initialized for group")
        else:
            logger.warning("WhatsApp bot not configured - WHATSAPP_GROUP_URL not set")

    def format_signal_message(self, signal: Dict) -> str:
        """
        Format a trading signal into a WhatsApp message

        Args:
            signal: Dictionary containing signal data with keys:
                - symbol: Trading pair/symbol
                - action: BUY or SELL
                - entry: Entry price
                - target: Target price
                - stop_loss: Stop loss price
                - confidence: AI confidence score (0-100)
                - timestamp: Signal generation time
                - status: Signal status (active, pending, etc.)

        Returns:
            Formatted message string
        """
        symbol = signal.get("symbol", "N/A")
        action = signal.get("action", "N/A").upper()
        entry = signal.get("entry", 0)
        target = signal.get("target", 0)
        stop_loss = signal.get("stop_loss", 0)
        confidence = signal.get("confidence", 0)
        timestamp = signal.get("timestamp", datetime.now().isoformat())

        # Format with emojis for better visibility
        action_emoji = "🟢" if action == "BUY" else "🔴"
        confidence_emoji = "⭐" * min(5, int(confidence / 20))

        message = f"""
{action_emoji} *GenX FX Trading Signal* {action_emoji}

📊 *Symbol:* {symbol}
📈 *Action:* {action}
💰 *Entry:* {entry}
🎯 *Target:* {target}
🛡️ *Stop Loss:* {stop_loss}

{confidence_emoji} *Confidence:* {confidence}%
⏰ *Time:* {timestamp}

_Generated by GenX AI Trading Platform_
""".strip()

        return message

    def send_signal(self, signal: Dict) -> bool:
        """
        Send a trading signal to the WhatsApp group

        Args:
            signal: Signal dictionary to send

        Returns:
            True if sent successfully, False otherwise
        """
        if not self.enabled:
            logger.warning("WhatsApp bot is not enabled - skipping message")
            return False

        try:
            message = self.format_signal_message(signal)
            logger.info(
                f"WhatsApp signal prepared for {signal.get('symbol', 'unknown')}"
            )

            # Note: Actual WhatsApp Web automation would require browser automation
            # For production, consider using WhatsApp Business API or third-party services
            logger.info(f"Signal message:\n{message}")
            logger.warning(
                "WhatsApp Web automation requires manual setup or WhatsApp Business API"
            )
            logger.info(f"Please manually share to group: {self.group_url}")

            return True

        except Exception as e:
            logger.error(f"Error sending WhatsApp signal: {e}")
            return False

    def send_notification(self, title: str, message: str) -> bool:
        """
        Send a general notification to the WhatsApp group

        Args:
            title: Notification title
            message: Notification message

        Returns:
            True if sent successfully, False otherwise
        """
        if not self.enabled:
            logger.warning("WhatsApp bot is not enabled - skipping notification")
            return False

        try:
            formatted_message = f"""
🔔 *{title}*

{message}

_GenX FX Trading Platform_
""".strip()

            logger.info(f"WhatsApp notification prepared: {title}")
            logger.info(f"Notification message:\n{formatted_message}")
            logger.info(f"Please manually share to group: {self.group_url}")

            return True

        except Exception as e:
            logger.error(f"Error sending WhatsApp notification: {e}")
            return False

    def send_status_update(
        self, service_name: str, status: str, details: str = ""
    ) -> bool:
        """
        Send a service status update to the WhatsApp group

        Args:
            service_name: Name of the service
            status: Status (online, offline, error, etc.)
            details: Additional details

        Returns:
            True if sent successfully, False otherwise
        """
        status_emoji = {
            "online": "✅",
            "offline": "❌",
            "error": "⚠️",
            "warning": "⚡",
            "info": "ℹ️",
        }.get(status.lower(), "📌")

        message = f"""
{status_emoji} *System Status Update*

*Service:* {service_name}
*Status:* {status.upper()}
{f"*Details:* {details}" if details else ""}

_GenX FX Trading Platform_
""".strip()

        return self.send_notification("Status Update", message)


# Create a singleton instance
whatsapp_bot = WhatsAppBot()


def send_signal(signal: Dict) -> bool:
    """Helper function to send a trading signal"""
    return whatsapp_bot.send_signal(signal)


def send_notification(title: str, message: str) -> bool:
    """Helper function to send a notification"""
    return whatsapp_bot.send_notification(title, message)


def send_status_update(service_name: str, status: str, details: str = "") -> bool:
    """Helper function to send a status update"""
    return whatsapp_bot.send_status_update(service_name, status, details)
